### ISSUE TITLE
Move Site Extension to nuget.org

### ISSUE THREAD

**Issue by davidebbo** [Stonefinch/AspNetUserMaintenanceAzureSiteExtension#1]
Please see https://github.com/Azure/app-service-announcements/issues/87 for detailed announcement.

**Important**: if your site extension is still relevant, you need to do this before June 1st 2018. Please let me know if you have any questions.

Thanks!

**Comment by aaronhoffman** [comment]
package updated, published to nuget.org, delisted from siteextensions.net

https://www.nuget.org/packages/AspNetUserMaintenanceAzureSiteExtension/

https://www.siteextensions.net/packages/AspNetUserMaintenanceAzureSiteExtension/0.0.1

![image](https://user-images.githubusercontent.com/109249/36762838-1f20d932-1beb-11e8-9961-5831a8e222cd.png)

**Comment by davidebbo** [comment]
That was fast, thanks!
